/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_Demo */

#ifndef _Included_demo_Demo
#define _Included_demo_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_Demo
 * Method:    predict
 * Signature: (Ljava/lang/String;III)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_demo_Demo_predict
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint);

/*
 * Class:     demo_Demo
 * Method:    load
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_demo_Demo_load
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
